name: 🙍‍♂️ User Story
description: Tuto šablonu použijte pro vytvoření požadavku na novou funkcionalitu.
title: "<Název User story>"
type: "User Story"
projects: ["Tajmac-ZPS/1"]
body:
  - type: textarea
    id: story
    attributes:
      label: User story
      value: |
        Jakožto: [typ uživatele]
        chci: [funkce]
        abych: [důvod/cíl]
    validations:
      required: true
  - type: textarea
    id: story-description
    attributes:
      label: Podrobnosti
      description: Uveďte další podrobnosti popisující požadovanou funkčnost.
    validations:
      required: false
  - type: textarea
    id: story-criteria
    attributes:
      label: Akceptační kritéria
      description: Definujte seznam nezbytných podmínek pro akceptování výsledného řešení.
      value: |
        - [ ] crit 1 
        - [ ] crit 2
    validations:
      required: true
  - type: textarea
    id: story-dod
    attributes:
      label: Definition of done
      description: Uveďte podmínky, za kterých lze úkol uzavřít. Upravte podle potřeby.
      value: |
         - [ ] Kód je implementován, zkontrolován, schválen a sloučen do hlavní větve.
         - [ ] Všechny implementované i manuální testy jsou úspěšné.
         - [ ] Všechna kritéria jsou akceptována.
         - [ ] Všechny podúlohy jsou uzavřené.
         - [ ] Uživatelská/Technická dokumentace je aktualizována.
    validations:
      required: true
