name: 🐞 Bug Report
description: Tuto šablonu použijte pro nahlášení nové chyby.
title: "<Název chyby>"
type: "Bug"
body:
  - type: textarea
    id: bug-description
    attributes:
      label: K čemu došlo?
      description: Jasný a stručný popis chyby.
      placeholder: Nezapomeňte uvést i očekávané chování!
    validations:
      required: true
  - type: textarea
    id: bug-steps
    attributes:
      label: Kroky k navození
      description: Podrobný popis kroků, kterými lze chybu navodit.
      value: |
        1. 
        2. 
        3. 
    validations:
      required: false
  - type: textarea
    id: bug-context
    attributes:
      label: Dodatečný kontext
      description: Zde můžete uvést další souvislosti problému.
    validations:
      required: false
