name: ☑️ Task
description: Tuto šablonu použijte pro jiný samostatný úkol.
title: "<Název úkolu>"
type: "Task"
body:
  - type: textarea
    id: task-description
    attributes:
      label: Popis
      description: Popište požadovaný úkol.
    validations:
      required: true
