name: ☑️ Task
description: Use this template for a separate task that should be traced.
title: "<Task title>"
type: "Task"
projects: ["Tajmac-ZPS/1"]
body:
  - type: textarea
    id: task-description
    attributes:
      label: Description
      description: Briefly describe the required task.
    validations:
      required: true
