name: 🗃️ Epic
description: Tuto šablonu použijte pro velký projekt nebo komplexní požadavek.
title: "<Název epiku>"
type: "Epic"
body:
  - type: textarea
    id: epic-description
    attributes:
      label: Popis
      description: Stručně popište projekt, jeho cíl a požadavky. Po vytvoření připojte související úkoly jako subissues.
    validations:
      required: true
